apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nopejs 
  janus-idp.io/tekton: nopejs
  backstage.io/kubernetes-id: nopejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nopejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  