apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nopejs
  janus-idp.io/tekton: nopejs
  backstage.io/kubernetes-id: nopejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nopejs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
