apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nopejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nopejs 
  name: nopejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nopejs
    weight: 100 
