apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nopejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nopejs 
  name: nopejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nopejs 
